# Generated by Django 4.2.2 on 2023-07-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
