# Generated by Django 4.2.2 on 2023-07-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_coupon_is_percentage_coupon_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='total_amount_cliamed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='total_cliamed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
