# Generated by Django 4.2.2 on 2023-07-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_coupon_is_active_coupon_total_amount_cliamed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
