# Generated by Django 4.2.2 on 2023-07-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='total_amount_cliamed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='total_cliamed',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
