# Generated by Django 4.2.2 on 2023-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_alter_coupon_total_amount_cliamed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
