# Generated by Django 4.2.2 on 2023-07-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_coupon_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='total_amount_cliamed',
            new_name='total_amount_claimed',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='total_cliamed',
            new_name='total_claimed',
        ),
    ]
