# Generated by Django 4.2.2 on 2023-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0010_rename_total_amount_cliamed_coupon_total_amount_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
