# Generated by Django 4.2.2 on 2023-07-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_usercoupon_amount_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
