# Generated by Django 4.2.2 on 2023-07-20 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0021_remove_category_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discount', '0014_usercoupon_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_claimed', models.IntegerField(default=0)),
                ('total_amount_claimed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiry', models.DateTimeField(default=datetime.date.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('discounted_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.categoryoffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
