# Generated by Django 4.2.2 on 2023-07-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0016_rename_expiry_categoryoffer_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='expiry_date',
            new_name='expiry',
        ),
    ]
