# Generated by Django 4.2.2 on 2023-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0017_rename_expiry_date_categoryoffer_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
