# Generated by Django 4.2.2 on 2023-07-20 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0018_categoryoffer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
