# Generated by Django 4.2.2 on 2023-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0019_alter_categoryoffer_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='expiry',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='expiry_date',
            field=models.DateField(default='2023-07-20'),
            preserve_default=False,
        ),
    ]
