# Generated by Django 4.2.2 on 2023-07-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0033_phonenumber_referred_by'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_variant_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.productvariantcolor')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist')),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_variant_color',
        ),
    ]
