# Generated by Django 4.2.2 on 2023-07-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_updated_at_wishlist_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
    ]
