# Generated by Django 4.2.2 on 2023-07-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_product_cartitem_productvariantcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='ProductVariantColor',
            new_name='product_variant_color',
        ),
    ]
