# Generated by Django 4.2.2 on 2023-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_productvariantcolor_cartitem_product_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price_before_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
