# Generated by Django 4.2.2 on 2023-07-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.colorvariant')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_deleted',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_deleted_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_left',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField( unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField( unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='admin_side.category'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
        migrations.AddField(
            model_name='variant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='admin_side.category'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.variant'),
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='variant',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='admin_side.variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_variant_color',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='admin_side.productvariantcolor'),
            preserve_default=False,
        ),
    ]
