# Generated by Django 4.2.2 on 2023-07-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_productvariant_productvariantcolor_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariant',
            name='variant',
        ),
    ]
