# Generated by Django 4.2.2 on 2023-07-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantcolor',
            name='color_variant',
        ),
        migrations.AddField(
            model_name='productvariantcolor',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_side.variant'),
            preserve_default=False,
        ),
    ]
