# Generated by Django 4.2.2 on 2023-07-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_productvariantcolor_color_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantcolor',
            name='variant',
        ),
    ]
