# Generated by Django 4.2.2 on 2023-07-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0008_remove_productvariantcolor_variant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantcolor',
            unique_together={('product_variant', 'color_variant')},
        ),
    ]
