# Generated by Django 4.2.2 on 2023-07-02 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0009_alter_productvariantcolor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(related_name='products', through='admin_side.ProductVariant', to='admin_side.variant'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_variant_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='admin_side.productvariantcolor'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='admin_side.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='admin_side.variant'),
        ),
        migrations.AlterField(
            model_name='productvariantcolor',
            name='color_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_colors', to='admin_side.colorvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantcolor',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_colors', to='admin_side.productvariant'),
        ),
    ]
