# Generated by Django 4.2.2 on 2023-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0010_alter_product_variants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
