# Generated by Django 4.2.2 on 2023-07-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0012_alter_product_is_active_alter_product_variants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_deleted',
            new_name='product_deleted',
        ),
    ]
