# Generated by Django 4.2.2 on 2023-07-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0013_rename_is_deleted_product_product_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcolor',
            name='slug',
            field=models.SlugField(default='DF'),
            preserve_default=False,
        ),
    ]
