# Generated by Django 4.2.2 on 2023-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0015_alter_productvariantcolor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcolor',
            name='variant_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
