# Generated by Django 4.2.2 on 2023-07-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0016_productvariantcolor_variant_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant')},
        ),
    ]
