# Generated by Django 4.2.2 on 2023-07-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0020_category_is_active_category_is_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_percentage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_amount_cliamed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_cliamed',
        ),
    ]
