# Generated by Django 4.2.2 on 2023-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0021_remove_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcolor',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
