# Generated by Django 4.2.2 on 2023-07-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0022_productvariantcolor_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantcolor',
            old_name='offer_price',
            new_name='mrp',
        ),
    ]
