# Generated by Django 4.2.2 on 2023-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0023_rename_offer_price_productvariantcolor_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcolor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
