# Generated by Django 4.2.2 on 2023-07-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0024_productvariantcolor_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantcolor',
            old_name='mrp',
            new_name='offer_price',
        ),
        migrations.RenameField(
            model_name='productvariantcolor',
            old_name='is_active',
            new_name='on_active',
        ),
    ]
