# Generated by Django 4.2.2 on 2023-07-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0025_rename_mrp_productvariantcolor_offer_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantcolor',
            old_name='on_active',
            new_name='on_offer',
        ),
    ]
