# Generated by Django 4.2.2 on 2023-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0027_productvariantcolor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantcolor',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
