# Generated by Django 4.2.2 on 2023-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0031_alter_phonenumber_total_amount_cliamed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
