# Generated by Django 4.2.2 on 2023-07-26 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0034_productvariantcolor_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariantcolor',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
