# Generated by Django 4.2.2 on 2023-07-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0035_productvariantcolor_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantcolor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariantcolor',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
