# Generated by Django 4.2.2 on 2023-08-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0037_alter_productvariantcolor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariantcolor',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
