# Generated by Django 4.2.2 on 2023-07-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
    ]
